# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardian < Formula
  desc "A constitutional engine for team agreements -- serverless, git-native, LLM-powered"
  homepage "https://github.com/AlexGladkov/guardian-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "8274c4d873660c89f50cd7d3926da1f3d3f9e43576678ba031c41e7bb2d47b64"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "2e26d3bee5eebff7335243a7b355189f3286541e50961a5e4a01f801695ae2ef"

      def install
        bin.install "guardian"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "ed3528b34b76a2291ad169f15c88b58ec4982d772433ef42729f7546031cf451"
      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "5efe4c9c3f8e125061ddf655e63baa3d429ee4a46afe6b6ac6def4ae7574ed42"
      def install
        bin.install "guardian"
      end
    end
  end

  test do
    system "#{bin}/guardian", "--help"
  end
end
