# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardian < Formula
  desc "A constitutional engine for team agreements -- serverless, git-native, LLM-powered"
  homepage "https://github.com/AlexGladkov/guardian-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "063d3af942c430040df55aadbf238ac10b1fde7f614a6a06666ee9545fe10e5f"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "6703bdc7e1d2cc6aabbac355446962fc47e66fd10b167dd02e933950b3ed3e22"

      def install
        bin.install "guardian"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "3046ab4870d1bc14969f158c4ceef7c1e5d671d820fbdd169270f02050d5a026"
      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexGladkov/guardian-cli/releases/download/v0.1.0/guardian-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "2ca37d2837fc351ea9d65467a79caff725413ff7704e80fa4b0f73d474418b5f"
      def install
        bin.install "guardian"
      end
    end
  end

  test do
    system "#{bin}/guardian", "--help"
  end
end
