# Generated by .github/workflows/release.yml from this template.
# Markers `@@FOO@@` are substituted at release time.

class Tokenplace < Formula
  desc "CLI-first AI infrastructure marketplace for the Russian engineering market"
  homepage "https://github.com/AlexGladkov/tokenplace"
  version "0.4.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.4.5/tokenplace-0.4.5-aarch64-apple-darwin.tar.gz"
      sha256 "c1753ae6c0950156dff924a18fbf05eab8c8f9eda9efc2a6e15cf637b5c34581"
    else
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.4.5/tokenplace-0.4.5-x86_64-apple-darwin.tar.gz"
      sha256 "e57a533e5af575c6bf954a5e9e58cacb8f4b25b4c22d8daff85ba9c5942b8e31"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.4.5/tokenplace-0.4.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "448be13897835d46118d83d38a24e9c0a592d082ca9cc695caf69abc0ab46794"
    else
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.4.5/tokenplace-0.4.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "23f87108a8c1e5e89d721f2b09f2ba5560d96f6466ebbd9f1d07ae01a6740eee"
    end
  end

  def install
    bin.install "tokenplace"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenplace --version")
  end
end
