# Generated by scripts/release-local.sh. Do not edit by hand.

class Tokenplace < Formula
  desc "CLI-first AI infrastructure marketplace for the Russian engineering market"
  homepage "https://github.com/AlexGladkov/tokenplace"
  version "0.35.0"

  depends_on "ollama"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.35.0/tokenplace-0.35.0-aarch64-apple-darwin.tar.gz"
      sha256 "f78efe056006d9b6cd355dfc8c1d8a5098226e9545b3aa3a6551d88a1b701f6b"
    else
      odie "tokenplace 0.35.0 ships no Intel-mac binary. Build from source: https://github.com/AlexGladkov/tokenplace"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.35.0/tokenplace-0.35.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0230c3b84047abd91959d046a303af7541d4ef66bc65282d9fed03cae447e8c9"
    else
      url "https://github.com/AlexGladkov/homebrew-tap/releases/download/tokenplace-v0.35.0/tokenplace-0.35.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f90393f5c019e29ddbde8ee7531c818f1db98aafe05e62d51dd15c1f6449b8af"
    end
  end

  def install
    bin.install "tokenplace"
    bin.install "tp-host-daemon"
  end

  def caveats
    <<~EOS
      A second binary `tp-host-daemon` is installed alongside `tokenplace`.
      It is invoked by launchd / systemd / Task Scheduler when you publish a
      model via the TUI — do not delete it.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenplace --version")
    assert_match version.to_s, shell_output("#{bin}/tp-host-daemon --version")
  end
end
